# Main compose file for ROS-master with the container from Dockerhub.
version: '2.1'

services:
  brain:
    image: windesheimwinny/keyboard:latest
    networks:
      - ros
    restart: always

networks:
  ros:
